### ISSUE TITLE
Dutch localization

### ISSUE THREAD

**Issue by DwarfyAssassin** [CraftedMods/nei-emmaitar#1]
I got bored so here is the dutch language file for the mod.
[nl_NL.txt](https://github.com/CraftedMods/nei-emmaitar/files/3816433/nl_NL.txt)

**Comment by CraftedMods** [comment]
Thanks, I'll implement it with the next version!

**Comment by CraftedMods** [comment]
Could you also translate that line: `neiEmmaitar.handler.paintings.loadingPlaceholder=Loading painting`? Thanks in advance.

**Comment by DwarfyAssassin** [comment]
Here you go
`neiEmmaitar.handler.paintings.loadingPlaceholder=Schilderijen aan het laden`
